import { OrbitControls } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import MainScene from 'components/MainScene/MainScene'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Next + R3F App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Canvas camera={{ position: [4, 2, 4] }}>
                    <MainScene />
                    <OrbitControls />
                </Canvas>
            </main>
        </div>
    )
}
